version: "3"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "tezbro"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  migrations:
    build:
      context: .
      dockerfile: migrations.dockerfile
    depends_on:
      - postgres

  tests:
    build:
      dockerfile: tests.dockerfile
      context: .
    depends_on:
      - migrations
